---
services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./WEB/app
        target: /srv/app
    ports:
      - "80:8000"
    networks:
      - frontend
      - backend
    depends_on:
      - backend

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./REST/app
        target: /srv/app
    networks:
      - backend

networks:
  frontend: {}
  backend: {}
